name: CI

on: [push, pull_request]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['2.7', '3.2']
        puppet: ['7.28.0', '8.4.0']
        exclude:
          - puppet: '7.28.0'
            ruby: '3.2'
          - puppet: '8.4.0'
            ruby: '2.7'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set-up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      env:
        PUPPET_VERSION: ${{matrix.puppet }}

    - name: Validate files
      run: bundle exec rake validate
      env:
        PUPPET_VERSION: ${{matrix.puppet }}

    - name: Run specs
      run: bundle exec rake spec
      env:
        PUPPET_VERSION: ${{matrix.puppet }}
