name: CI

on: [push, pull_request]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.2']
        puppet: ['8.10.0']
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set-up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
      env:
        PUPPET_VERSION: ${{matrix.puppet }}

    - name: Validate files
      run: bundle exec rake validate
      env:
        PUPPET_VERSION: ${{matrix.puppet }}

    - name: Run specs
      run: bundle exec rake spec
      env:
        PUPPET_VERSION: ${{matrix.puppet }}
